dist: trusty
language: php
php:
- 7.2
- 7.3
- 7.4
- hhvm
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
before_script:
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
- touch .env
script:
- vendor/bin/phpcs --standard=psr2 src/
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
- |
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi
env:
  global:
  - secure: hm+UTYHu9VOmf0fYsBq/cjuMZXgW3Hpxk0p1ADhXu5Bp84ZZ+D91VDaOrIpN24DI0c2N3Tf2wDP3fPTMfj2Up0XIkMEkFTtyRdguqDudcu6S5KQoq+ZEE4Jn18a0xhVMOL6vDXu2fn84BBcQ1TcHTDdgWIX9kLPbhCmdrOLUMDJqgH+4brxAaU6RF3voCRv211i/EVivs1HNLaBdFnoe/+SmkuaXjCVMJOBEZur7ezTYdR2Aq9dqGn/NnleYuF3P+rJJrm6goM60WivDJ4r6Gl8qylMqKSN+O5Nw2sEFtgv8eRvd3CYZGI6E6jm1U94Yx4LKoDbnXwHmrmPrRdIORngl/xSosW0eHuuEV32Pxx+nYRxbJBVYxB55oOCpZ+BkP8dr0cCLNHFh9PpIlQuzeS19JC8pORx9ezStIrMoGVjBIisSq0P21VL8l3gQaHzpi+Gl/h1ldtTCdXnvSZdJ4zGuhlNnZv+URQU7qAntbflemlZNnf0JhtDAZ41rg6/3Nh7APbvFmicqgammHFuflAKwf1MZDz2VZ8HHJ9CP0pYywOdgLgqTi60xsE+U8lrSc3+LFUVdn/Ijxxnoq3JnJudi2H13vxDwa0R1M3N5d087aSI5FRDzpMZOJbfXqdvu68xb+881+tmmmFxDdazB3TUK42o3uvDrhgFawjrG0NI=
  - secure: DlkJBWbunNApP3JDskeJANaWdLEWP/RdJmvocCD9v+eUrjTzPP1Gkc5CDqbMDNw7sSqZifXJfSA3o2u818qNPjd9eInzRsUYvPNapnk9d5DhsYEz956Hq6fnSypJrd//zP5dyB2iqnSUep66+jomgtKwqjCNODOvdK92rPLpTqTSmnOC2T9wUK7TJMEC2IuJ8C459rhp6+YFfg73wpHQNGZMeaOBjYkowJMk+P7I51Wk1BkRQR/gq80D/d0fNUKEfvH7YRhB4+249FDzfwWRQvBBO14GjX0l+3YCJsVIMGeAo1CaNj7pZoVTesINdqJzlY1pNE1j6heZRX0M49GJH5sMwd4TXFhomJv9KddIS70lEpyX6Why/D6htm84syYaYRGHJKYHtZFHvXOwxn581o/H1fqj/1ISNEg7GgWvUF8Tetvu67/ifbLfuvkKf6vJZw7bZc2W8H7BS2ybHFkKDYYMUu75yNVc4Q9joKes7+/jDWJWEnco/QtO6dM2cyNKqNLzEY0KwkNCcqXqY42Z4e/epsvFr5zuXDQMwho4yjYIqHMe4robDCXpsNMiFDkrnjLw7mOYdsq87aRrmYyRoptLVLn+4pHZaivHGvWGV4DWd4offJPtrSBSUmsRAmIC0fEyYpQNiTfAb7OHFPpPyU6Zxx7u1QYt3uLM85dOYvM=
  - secure: qIv3UtZOq8ONKHuHfy0zB1ick89i01f/UrVWtUiiSx9DK8VNnQoekpotKCdy+gGFKY4AElsW6LapUCdxfGr5CQyPHUbFmLX7DteiYjDf4i7PDsFu6ccR4+YjrEZPdG7HK4cUGshwSfMDitmaQ8T0MY2h+lyjzx+7E/raDFqmDht/O2TNLR2N1dKSZ3ZlDgeiTxX8jk0Y8fucT7ZEu0pc64KF1L4YHQ9r1ZPsdrCapLScdr/RJIYVaJgPv1Q1TymMRvkwaDaf5HhvE25wTGIKzjFxoe818+2O4ey+UN94eQ9gAfz6BBnEK8JQHcKNywvJl1yhSSLWmwlcnMySmWzhdRQlltNpeXmydh+zyHRrOFTZRYzrjPGjX6XQg4Hc9YVgW+QjZayxwZotv7AjXFyDuFaL0ywc6bHSWnxbDy78rj6kT6AU+/W3M+bELU85X7BKZeabUHhpwWKwOn+T4psIegBr3lK+4mzslixaZB4XtPvm6LQ/chn52gRTEWlgTPaSd5PijlXmK55M71+lxxj1IztH86o0EclBbcicbSsIee2Wi+M2JiYvl6C0kFni/xiiOBoZIPIgbOXGCDB9jdFrD19fvJ5N0AVd5zuh/f1GPxEKc1R/v8Oa83CZorcFKo2Evup8b6RRECAk6k1jSvPGT7ypgZS0AysqUmbuVgCbXlA=
  - secure: pDQ0o3K9cnrBGBbwRWNbKwtkGFuSve32TbO6BkXs3bsCjj1e/DOoJ97nPMUkpNw6Hot1IpGk1zFXPaJnCnJUp9bEhp6TdzKuDQsLT5TvhwpDx7BGY6q/wIx5egt0wPtQQKPVs8eZdwkjw2DHFfT7hkiCDJ4qS2oVb8vYspfrT3hSxQrrJg43qKfzwwS/YjTFE61Yc91f+jdcZ9h14VVGAAx/KJyegyLdp2cUtVEhZXEPFiBsvUz20IXsrodBqi81w4tdAGJyrbqZUMg8KSwBxDFJpPatnu0suvy/G/eG7th3Wee2d0oI+5fD63cBKjUk0qORwBHQZ4sBWcZ4NM8a1Zixlu2GYoRSStO3go3Ld9qCUnYjEOCT6P2kjuuGGN2pIMZEGT3nuwp0KxwjVbi6SICU9f3/rtnktSts3NX547OFI/f5iat6uhB92m0HDTx3caNc/4hFuxxfeYh7r3u3ZyvxVFECuk/HDRvA8twEdveUQSL5osN4UgqQLb5IjROzOjH60iU4RlTf1F4kJV21/EhsN0rTjPMFmBOwTn2Kvc/puv8OVk5T083WS4yLA/3n0h+lxoZQH+ANwmB8UcF5FZGfOJq4FOaTxTGfu2q/pels0tZ+famyGdrXEISfM8kW4z1QR1/BpPrc0UW0DUvizSseI89cUQKmQtNSlJBv9So=
