dist: trusty
language: php
php:
- 7.2
- 7.3
- 7.4
- hhvm
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
before_script:
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
- touch .env
script:
- vendor/bin/phpcs --standard=psr2 src/
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
- |
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi
env:
  global:
  - secure: hr37IltPozJx5OjLOyi6uNzZfeeE6qNDKNrzf1NgE56vBqLXNpxXjAd4AMOdDeQAe6vOVNfM2o7yFju0OSlgS4ljkZFHeb5SEFn3qO7T/xz+J9S6Hv3pEZkqDVyocvStzg5bf5kJiJs0FD24B3sR21VaQyIv9I/JBDgxJs9NimpM8aabwoNbLh7Fus2ln9SlD/sXV7Sfz1l9Z82XpNTB/92lHzeETJvnFKI3WPybpCE78yPU9NO5CAEnA9fVx+UWGcZJXxd7QYNjYZFTPjVEyvhNeVKgro6ON33mXaVtE1PL1Lz2Ee73jmM05uHj/BV5qYpCCl97xmihC1x2mRO+lGh97SKsVZi/frhLcc228m+AZq4XIRfGVBSm1eAX6HXnZ6zmkWoyY7R5dVhg8EsLyudyleREkrxUMyERQjMc4xTKnpnGbXM0dBCsHOD7LGLtFN7J8khcm+5Imb6PXvMq6Vvj2G4FzIaoF4JVNcMJS7YIhyOhis6bjH4wnOSpE1/mGHxcgt8y3BPVJ8aUihaNcMq0pUf3ui+hQzffP5Q/afUscnugm0qeN2iMJisc/tZtqSnojBQzbdKV/2omyFyqLNAJx6ItRyAXAFUIA68Sv96s+pwFFyEKLpQPkOMOoZxpqHGSa+LI07UxCSUOxcTJVAv3LdYx0B1kL4SxzgxDa/M=
  - secure: g0rx6PBY+9U0yg4cztH8cexg5Yr30SfH2m4vDybwEci/3qwc4mwZ6QAHVjS4z/QKQurUPwYdp+G/TifqovbI0xSkF36FUjZdMy04Ax/ote7XVS2YoIKrbLBqOwzctYcf+ZQwOIFSDrblzW48nAk8iqNVTBaqiiP+BZ3t0qcNSEyOjEOLaPPZv1QH5rJoh8d5ViPLrtD0LXn9Er/rxWn4nmcDYeERyOWTyKKGccIPq1yRQ44JqNLp9w9HNwDGcPoKmzEG3BSfTYFAf5Ziwie953DQzHfVtD1WsPe47G8meCAO37JjUZYZ317M7eeiea3CUbI+QoBKJZHJk70JlYDH52PHsElA43gCv+v7YxkZ5M8llpefvs4oM3gBY+23/R0rt4PC1hWKkkc/17LrUYqV9xZYu/qNjVxvc9/GLj5GfCe44nA+EAn/PEc7Mi+hjJarR3xLjkODiT3NfSdqyUWENZe/mU0nrJ4VGKAd81/fdHHAr0C6X997dZNfZqVdWB5K8qATeddTWzTB9Hjj1niiKIuQ6kUUZLyM+2K+Feu6P9SBgbzyD5NI6AnlpxYwBFK57Tm8LXSxmLfWRnpliYWHRu82PbhEGQhAntdLfAaw2DLQQAg8bbsJY2PS68hoBqGpAM1wKXLPkzUH3I29CCzdJU5GI5QPaMnw5PziHkdGrjk=
  - secure: WoNOZewI91TwldTNFLQy6wrGWAF/dKzJh0wUoyfXWXOh/AqohuyYwrGhhvOg0JMKLp17/Y2btbJJkmGZRCr8d55WrxuxBMrT0FYe4U1fqv9p88hR82tFR+NWaGKjQL4CnxzMcJ127i4RhU9GYgDBTE1AvlohGMFkvYofNMM3QtZo6Lxp5uo3LT2WsJ+8LrFUFkiESBQcRsIeGsh485lQkOM/65kNcdJjPQxDD19iHvWYkibG1lDPficgJuhpua7+vrWrkvwur59IOJ4D1dM6iDyH+cdCG3pNp5D7TYUqF3cEG5uqBNVXSE97ZQmA6+fqnT9x9265yAQhedYZSHnp+/mbRPKGu0IS55SlmyyLgKEQQndsVPSbzECUfXQ+jyVB12RZ9dCKVsEFaPvPmto5F1h80Zve20WLii38vIpqR+3+jV2H1LVIo/M4/OBtnP6ARxHb42s/myLjygcffKohlq5B088yumoS1dxk6SH5EGWMaGgb3D2/vTxJrXN2iolpzXeXwu2/zhgFpMTAvEbcuq5exed0CKx5JQ7ej5Kp9v6WnB30tlRQYA1dslDbFxjqutscFIqL4KkdCa7/K65XpkwXDHYfmxEDkgYLfGrXmZMcb3NFJWs5lHOEbfiF9gQ3kHB2j3uywhj9RbMZ0cONrAlDpzgyqNADrgqKVK7p32E=
  - secure: YgCQBZ5/p3keB4EHT8sm+W1gRqP4eVS1lv22QF5kFR8bT81iVVD1Xd7uGPs72x6xtTni3ggBm9JGn+y0Y3NwIA3da0gmcEoxpkDjAuy2p34oOSCRyYSGqNyl6HpneTfmQGPKfBL6OPYrQ5DWcB8y8wE/vurxwFEiWPaWMmxb1++fda6cjsiT/tRS2u8TRRtMw/MUIS9e+GBejTIUOtTxS5FrbsIU/OWxU34Px6A0EYMEP4eRaNGN0cDjXwVHu9JfpSN1vuZ78QphGdc6ImSoJsaeu2tf5vMNrx/jE4ACPDT+CD/uWFTC5WVmN6U+iHSIld9QW7dv++xADgfFTnufOPdgM2r8iLcnCEQ0/hDLUa/a9vqHO1VbJn1dKV9iK/mN8T4kpmEj/L2uxrAfCG0tlTkpe14hs77DdqYNxF826I01y4LaD/sgKci8CBSbSvaw3zvrskaxHJQjnT/bEWOnojeG/GoRyYHMVCOgJ5oE2QRVxeaQ6SiG2X/my8HZ6yNfTgZ9/a+sWn2umWv1GCU1GUtDpvb8NG9w1kJcHo5S9ZGPD7sr1cikpQEf6PNCJ33lC+y985BSDTeO9RH6tRyc0Hz02titaPgp5nzzjRVq3PSRPZDnCEfJm12Vn3EYHtDbW6Jl8Aswd8VZ4XrO9gnJM2eLw2LhX2NFnU2DitWa0Rw=
