dist: trusty
language: php
php:
- 7.2
- 7.3
- 7.4
- hhvm
cache:
  directories:
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.2
    env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
before_script:
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
- touch .env
script:
- vendor/bin/phpcs --standard=psr2 src/
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
after_script:
- |
  if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' ]]; then
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  fi
env:
  global:
  - secure: hm+UTYHu9VOmf0fYsBq/cjuMZXgW3Hpxk0p1ADhXu5Bp84ZZ+D91VDaOrIpN24DI0c2N3Tf2wDP3fPTMfj2Up0XIkMEkFTtyRdguqDudcu6S5KQoq+ZEE4Jn18a0xhVMOL6vDXu2fn84BBcQ1TcHTDdgWIX9kLPbhCmdrOLUMDJqgH+4brxAaU6RF3voCRv211i/EVivs1HNLaBdFnoe/+SmkuaXjCVMJOBEZur7ezTYdR2Aq9dqGn/NnleYuF3P+rJJrm6goM60WivDJ4r6Gl8qylMqKSN+O5Nw2sEFtgv8eRvd3CYZGI6E6jm1U94Yx4LKoDbnXwHmrmPrRdIORngl/xSosW0eHuuEV32Pxx+nYRxbJBVYxB55oOCpZ+BkP8dr0cCLNHFh9PpIlQuzeS19JC8pORx9ezStIrMoGVjBIisSq0P21VL8l3gQaHzpi+Gl/h1ldtTCdXnvSZdJ4zGuhlNnZv+URQU7qAntbflemlZNnf0JhtDAZ41rg6/3Nh7APbvFmicqgammHFuflAKwf1MZDz2VZ8HHJ9CP0pYywOdgLgqTi60xsE+U8lrSc3+LFUVdn/Ijxxnoq3JnJudi2H13vxDwa0R1M3N5d087aSI5FRDzpMZOJbfXqdvu68xb+881+tmmmFxDdazB3TUK42o3uvDrhgFawjrG0NI=
  - secure: DlkJBWbunNApP3JDskeJANaWdLEWP/RdJmvocCD9v+eUrjTzPP1Gkc5CDqbMDNw7sSqZifXJfSA3o2u818qNPjd9eInzRsUYvPNapnk9d5DhsYEz956Hq6fnSypJrd//zP5dyB2iqnSUep66+jomgtKwqjCNODOvdK92rPLpTqTSmnOC2T9wUK7TJMEC2IuJ8C459rhp6+YFfg73wpHQNGZMeaOBjYkowJMk+P7I51Wk1BkRQR/gq80D/d0fNUKEfvH7YRhB4+249FDzfwWRQvBBO14GjX0l+3YCJsVIMGeAo1CaNj7pZoVTesINdqJzlY1pNE1j6heZRX0M49GJH5sMwd4TXFhomJv9KddIS70lEpyX6Why/D6htm84syYaYRGHJKYHtZFHvXOwxn581o/H1fqj/1ISNEg7GgWvUF8Tetvu67/ifbLfuvkKf6vJZw7bZc2W8H7BS2ybHFkKDYYMUu75yNVc4Q9joKes7+/jDWJWEnco/QtO6dM2cyNKqNLzEY0KwkNCcqXqY42Z4e/epsvFr5zuXDQMwho4yjYIqHMe4robDCXpsNMiFDkrnjLw7mOYdsq87aRrmYyRoptLVLn+4pHZaivHGvWGV4DWd4offJPtrSBSUmsRAmIC0fEyYpQNiTfAb7OHFPpPyU6Zxx7u1QYt3uLM85dOYvM=
  - TEST_TABLE_NAME='Table\ 1'
  - TEST_VIEW_NAME='Grid\ View'
